# Generated by Django 4.2.4 on 2024-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0002_remove_product_image_remove_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
